-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."teams_users" add column "role" text
--  not null default 'member';
