table:
  name: copy_configurations
  schema: public
object_relationships:
  - name: project
    using:
      foreign_key_constraint_on: project_id
insert_permissions:
  - role: user
    permission:
      check:
        project:
          teams_projects:
            team:
              teams_users:
                user_id:
                  _eq: X-Hasura-User-Id
      columns:
        - project_id
    comment: ""
select_permissions:
  - role: user
    permission:
      columns:
        - character_count
        - brand_tone
        - perspective
        - template_type
        - tone
        - created_at
        - updated_at
        - project_id
      filter:
        project:
          teams_projects:
            team:
              teams_users:
                user_id:
                  _eq: X-Hasura-User-Id
    comment: ""
update_permissions:
  - role: user
    permission:
      columns:
        - brand_tone
        - character_count
        - perspective
        - template_type
        - tone
      filter:
        project:
          teams_projects:
            team:
              teams_users:
                user_id:
                  _eq: X-Hasura-User-Id
      check: null
    comment: ""
