-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE facebook_audiences ALTER COLUMN facebook_positions SET DEFAULT ARRAY['feed'];
